FROM tailscale/tailscale:v1.102.3 AS tailscale

FROM alpine:3.22
RUN apk add --no-cache ca-certificates curl
COPY --from=tailscale /usr/local/bin/tailscale /usr/local/bin/tailscale
COPY --from=tailscale /usr/local/bin/tailscaled /usr/local/bin/tailscaled
